FROM nginx

ENV CERTS_PATH /etc/nginx/certs

RUN apt-get update && apt-get install -y openssl \
  && mkdir -p ${CERTS_PATH} \
  && openssl req -subj '/CN=localhost' -x509 -newkey rsa:4096 -nodes -keyout ${CERTS_PATH}/key.pem -out ${CERTS_PATH}/cert.pem -days 365

COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx-sites.conf.template /etc/nginx/conf.d/default.conf

EXPOSE 80 443
